version: '3'

services:
  spring-boot-rest-api-app:
    image: challenge-docker-image
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 7070:8080
    volumes:
      - /data/challenge