#version: '3'
#
#services:
#  spring-boot-rest-api-app:
#    image: challenge-docker-image
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    ports:
#      - 9080:8080
#    depends_on:
#      - db
#    volumes:
#      - /data/challenge
#  db:
#    image: postgres
#    ports:
#      - 5432:5432
#    environment:
#      - POSTGRES_PASSWORD=password
#      - POSTGRES_USER=postgres
#      - POSTGRES_DB=challenge_db

version: "3"
services:
  postgres:
    image: postgres:latest
    network_mode: bridge
    container_name: postgres
    volumes:
      - postgres-data:C:/Users/Evandro/Documents/postgres/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    restart: unless-postgres
  # APP*****************************************
  springbootapp:
    image: challenge:latest
    build:
      context: ./
      dockerfile: Dockerfile
    network_mode: bridge
    container_name: challenge
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
volumes:
  postgres-data:
    external: true
