INSERT INTO `recifedespesas`.`despesa`
(`id`,
`acao_codigo`,
`acao_nome`,
`ano_movimentacao`,
`categoria_economica_codigo`,
`categoria_economica_nome`,
`credor_codigo`,
`credor_nome`,
`elemento_codigo`,
`elemento_nome`,
`empenho_ano`,
`empenho_modalidade_codigo`,
`empenho_modalidade_nome`,
`empenho_numero`,
`fonte_recurso_codigo`,
`fonte_recurso_nome`,
`funcao_codigo`,
`funcao_nome`,
`grupo_despesa_codigo`,
`grupo_despesa_nome`,
`indicador_subempenho`,
`mes_movimentacao`,
`modalidade_aplicacao_codigo`,
`modalidade_aplicacao_nome`,
`modalidade_licitacao_codigo`,
`modalidade_licitacao_nome`,
`orgao_codigo`,
`orgao_nome`,
`programa_codigo`,
`programa_nome`,
`subelemento_codigo`,
`subelemento_nome`,
`subempenho`,
`subfuncao_codigo`,
`subfuncao_nome`,
`unidade_codigo`,
`unidade_nome`,
`valor_empenhado`,
`valor_liquidado`,
`valor_pago`)
VALUES
(<{id: }>,
<{acao_codigo: }>,
<{acao_nome: }>,
<{ano_movimentacao: }>,
<{categoria_economica_codigo: }>,
<{categoria_economica_nome: }>,
<{credor_codigo: }>,
<{credor_nome: }>,
<{elemento_codigo: }>,
<{elemento_nome: }>,
<{empenho_ano: }>,
<{empenho_modalidade_codigo: }>,
<{empenho_modalidade_nome: }>,
<{empenho_numero: }>,
<{fonte_recurso_codigo: }>,
<{fonte_recurso_nome: }>,
<{funcao_codigo: }>,
<{funcao_nome: }>,
<{grupo_despesa_codigo: }>,
<{grupo_despesa_nome: }>,
<{indicador_subempenho: }>,
<{mes_movimentacao: }>,
<{modalidade_aplicacao_codigo: }>,
<{modalidade_aplicacao_nome: }>,
<{modalidade_licitacao_codigo: }>,
<{modalidade_licitacao_nome: }>,
<{orgao_codigo: }>,
<{orgao_nome: }>,
<{programa_codigo: }>,
<{programa_nome: }>,
<{subelemento_codigo: }>,
<{subelemento_nome: }>,
<{subempenho: }>,
<{subfuncao_codigo: }>,
<{subfuncao_nome: }>,
<{unidade_codigo: }>,
<{unidade_nome: }>,
<{valor_empenhado: }>,
<{valor_liquidado: }>,
<{valor_pago: }>);