INSERT INTO despesa
(id, acao_codigo, acao_nome, ano_movimentacao, categoria_economica_codigo, categoria_economica_nome, credor_codigo, credor_nome, elemento_codigo, elemento_nome, empenho_ano, empenho_modalidade_codigo, empenho_modalidade_nome, empenho_numero, fonte_recurso_codigo, fonte_recurso_nome, funcao_codigo, funcao_nome, grupo_despesa_codigo, grupo_despesa_nome, indicador_subempenho, mes_movimentacao, modalidade_aplicacao_codigo, modalidade_aplicacao_nome, modalidade_licitacao_codigo, modalidade_licitacao_nome, orgao_codigo, orgao_nome, programa_codigo, programa_nome, subelemento_codigo, subelemento_nome, subempenho, subfuncao_codigo, subfuncao_nome, unidade_codigo, unidade_nome, valor_empenhado, valor_liquidado, valor_pago)
VALUES(1, 2064, 'ASSESSORAMENTO GOVERNAMENTAL', 2019, 3, 'DESPESAS CORRENTES', 0, 'CREDOR NÃO INFORMADO', 11, 'VENCIMENTOS E VANTAGENS FIXAS - PESSOAL CIVIL', 2019, 0, 'SEM TIPO INFORMADO', 1, 100, 'RECURSOS ORDINÁRIOS - NÃO VINCULADOS', 4, 'ADMINISTRAÇÃO', 1, 'PESSOAL E ENCARGOS SOCIAIS', 'x', 5, 90, 'APLICAÇÕES DIRETAS', 0, 'NÃO INFORMADA', 9, 'ASSESSORIA ESPECIAL DO PREFEITO', 2160, 'GESTÃO DAS POLÍTICAS MUNICIPAIS', 1, 'VENCIMENTOS E SALÁRIOS', 85, 122, 'ADMINISTRAÇÃO GERAL', 9.01, 'ASSESSORIA ESPECIAL DO PREFEITO - ADMINISTRAÇÃO DIRETA', '4560,91', '4560,91', 4560.91);
INSERT INTO despesa
(id, acao_codigo, acao_nome, ano_movimentacao, categoria_economica_codigo, categoria_economica_nome, credor_codigo, credor_nome, elemento_codigo, elemento_nome, empenho_ano, empenho_modalidade_codigo, empenho_modalidade_nome, empenho_numero, fonte_recurso_codigo, fonte_recurso_nome, funcao_codigo, funcao_nome, grupo_despesa_codigo, grupo_despesa_nome, indicador_subempenho, mes_movimentacao, modalidade_aplicacao_codigo, modalidade_aplicacao_nome, modalidade_licitacao_codigo, modalidade_licitacao_nome, orgao_codigo, orgao_nome, programa_codigo, programa_nome, subelemento_codigo, subelemento_nome, subempenho, subfuncao_codigo, subfuncao_nome, unidade_codigo, unidade_nome, valor_empenhado, valor_liquidado, valor_pago)
VALUES(2, 2064, 'ASSESSORAMENTO GOVERNAMENTAL', 2019, 3, 'DESPESAS CORRENTES', 0, 'CREDOR NÃO INFORMADO', 11, 'VENCIMENTOS E VANTAGENS FIXAS - PESSOAL CIVIL', 2019, 0, 'SEM TIPO INFORMADO', 2, 100, 'RECURSOS ORDINÁRIOS - NÃO VINCULADOS', 4, 'ADMINISTRAÇÃO', 1, 'PESSOAL E ENCARGOS SOCIAIS', 'x', 1, 90, 'APLICAÇÕES DIRETAS', 0, 'NÃO INFORMADA', 9, 'ASSESSORIA ESPECIAL DO PREFEITO', 2160, 'GESTÃO DAS POLÍTICAS MUNICIPAIS', 5, 'INCORPORAÇÕES', 81, 122, 'ADMINISTRAÇÃO GERAL', 9.01, 'ASSESSORIA ESPECIAL DO PREFEITO - ADMINISTRAÇÃO DIRETA', '604,50', '604,50', 604.5);
INSERT INTO despesa
(id, acao_codigo, acao_nome, ano_movimentacao, categoria_economica_codigo, categoria_economica_nome, credor_codigo, credor_nome, elemento_codigo, elemento_nome, empenho_ano, empenho_modalidade_codigo, empenho_modalidade_nome, empenho_numero, fonte_recurso_codigo, fonte_recurso_nome, funcao_codigo, funcao_nome, grupo_despesa_codigo, grupo_despesa_nome, indicador_subempenho, mes_movimentacao, modalidade_aplicacao_codigo, modalidade_aplicacao_nome, modalidade_licitacao_codigo, modalidade_licitacao_nome, orgao_codigo, orgao_nome, programa_codigo, programa_nome, subelemento_codigo, subelemento_nome, subempenho, subfuncao_codigo, subfuncao_nome, unidade_codigo, unidade_nome, valor_empenhado, valor_liquidado, valor_pago)
VALUES(3, 2064, 'ASSESSORAMENTO GOVERNAMENTAL', 2019, 3, 'DESPESAS CORRENTES', 0, 'CREDOR NÃO INFORMADO', 11, 'VENCIMENTOS E VANTAGENS FIXAS - PESSOAL CIVIL', 2019, 0, 'SEM TIPO INFORMADO', 2, 100, 'RECURSOS ORDINÁRIOS - NÃO VINCULADOS', 4, 'ADMINISTRAÇÃO', 1, 'PESSOAL E ENCARGOS SOCIAIS', 'x', 3, 90, 'APLICAÇÕES DIRETAS', 0, 'NÃO INFORMADA', 9, 'ASSESSORIA ESPECIAL DO PREFEITO', 2160, 'GESTÃO DAS POLÍTICAS MUNICIPAIS', 5, 'INCORPORAÇÕES', 83, 122, 'ADMINISTRAÇÃO GERAL', 9.01, 'ASSESSORIA ESPECIAL DO PREFEITO - ADMINISTRAÇÃO DIRETA', '604,50', '604,50', 604.5);
INSERT INTO despesa
(id, acao_codigo, acao_nome, ano_movimentacao, categoria_economica_codigo, categoria_economica_nome, credor_codigo, credor_nome, elemento_codigo, elemento_nome, empenho_ano, empenho_modalidade_codigo, empenho_modalidade_nome, empenho_numero, fonte_recurso_codigo, fonte_recurso_nome, funcao_codigo, funcao_nome, grupo_despesa_codigo, grupo_despesa_nome, indicador_subempenho, mes_movimentacao, modalidade_aplicacao_codigo, modalidade_aplicacao_nome, modalidade_licitacao_codigo, modalidade_licitacao_nome, orgao_codigo, orgao_nome, programa_codigo, programa_nome, subelemento_codigo, subelemento_nome, subempenho, subfuncao_codigo, subfuncao_nome, unidade_codigo, unidade_nome, valor_empenhado, valor_liquidado, valor_pago)
VALUES(4, 2064, 'ASSESSORAMENTO GOVERNAMENTAL', 2019, 3, 'DESPESAS CORRENTES', 0, 'CREDOR NÃO INFORMADO', 11, 'VENCIMENTOS E VANTAGENS FIXAS - PESSOAL CIVIL', 2019, 0, 'SEM TIPO INFORMADO', 2, 100, 'RECURSOS ORDINÁRIOS - NÃO VINCULADOS', 4, 'ADMINISTRAÇÃO', 1, 'PESSOAL E ENCARGOS SOCIAIS', 'x', 7, 90, 'APLICAÇÕES DIRETAS', 0, 'NÃO INFORMADA', 9, 'ASSESSORIA ESPECIAL DO PREFEITO', 2160, 'GESTÃO DAS POLÍTICAS MUNICIPAIS', 5, 'INCORPORAÇÕES', 87, 122, 'ADMINISTRAÇÃO GERAL', 9.01, 'ASSESSORIA ESPECIAL DO PREFEITO - ADMINISTRAÇÃO DIRETA', '604,50', '604,50', 604.5);
INSERT INTO despesa
(id, acao_codigo, acao_nome, ano_movimentacao, categoria_economica_codigo, categoria_economica_nome, credor_codigo, credor_nome, elemento_codigo, elemento_nome, empenho_ano, empenho_modalidade_codigo, empenho_modalidade_nome, empenho_numero, fonte_recurso_codigo, fonte_recurso_nome, funcao_codigo, funcao_nome, grupo_despesa_codigo, grupo_despesa_nome, indicador_subempenho, mes_movimentacao, modalidade_aplicacao_codigo, modalidade_aplicacao_nome, modalidade_licitacao_codigo, modalidade_licitacao_nome, orgao_codigo, orgao_nome, programa_codigo, programa_nome, subelemento_codigo, subelemento_nome, subempenho, subfuncao_codigo, subfuncao_nome, unidade_codigo, unidade_nome, valor_empenhado, valor_liquidado, valor_pago)
VALUES(5, 2064, 'ASSESSORAMENTO GOVERNAMENTAL', 2019, 3, 'DESPESAS CORRENTES', 0, 'CREDOR NÃO INFORMADO', 11, 'VENCIMENTOS E VANTAGENS FIXAS - PESSOAL CIVIL', 2019, 0, 'SEM TIPO INFORMADO', 2, 100, 'RECURSOS ORDINÁRIOS - NÃO VINCULADOS', 4, 'ADMINISTRAÇÃO', 1, 'PESSOAL E ENCARGOS SOCIAIS', 'x', 9, 90, 'APLICAÇÕES DIRETAS', 0, 'NÃO INFORMADA', 9, 'ASSESSORIA ESPECIAL DO PREFEITO', 2160, 'GESTÃO DAS POLÍTICAS MUNICIPAIS', 5, 'INCORPORAÇÕES', 89, 122, 'ADMINISTRAÇÃO GERAL', 9.01, 'ASSESSORIA ESPECIAL DO PREFEITO - ADMINISTRAÇÃO DIRETA', '604,50', '604,50', 604.5);
INSERT INTO despesa
(id, acao_codigo, acao_nome, ano_movimentacao, categoria_economica_codigo, categoria_economica_nome, credor_codigo, credor_nome, elemento_codigo, elemento_nome, empenho_ano, empenho_modalidade_codigo, empenho_modalidade_nome, empenho_numero, fonte_recurso_codigo, fonte_recurso_nome, funcao_codigo, funcao_nome, grupo_despesa_codigo, grupo_despesa_nome, indicador_subempenho, mes_movimentacao, modalidade_aplicacao_codigo, modalidade_aplicacao_nome, modalidade_licitacao_codigo, modalidade_licitacao_nome, orgao_codigo, orgao_nome, programa_codigo, programa_nome, subelemento_codigo, subelemento_nome, subempenho, subfuncao_codigo, subfuncao_nome, unidade_codigo, unidade_nome, valor_empenhado, valor_liquidado, valor_pago)
VALUES(6, 2064, 'ASSESSORAMENTO GOVERNAMENTAL', 2019, 3, 'DESPESAS CORRENTES', 0, 'CREDOR NÃO INFORMADO', 11, 'VENCIMENTOS E VANTAGENS FIXAS - PESSOAL CIVIL', 2019, 0, 'SEM TIPO INFORMADO', 4, 100, 'RECURSOS ORDINÁRIOS - NÃO VINCULADOS', 4, 'ADMINISTRAÇÃO', 1, 'PESSOAL E ENCARGOS SOCIAIS', 'x', 1, 90, 'APLICAÇÕES DIRETAS', 0, 'NÃO INFORMADA', 9, 'ASSESSORIA ESPECIAL DO PREFEITO', 2160, 'GESTÃO DAS POLÍTICAS MUNICIPAIS', 31, 'GRATIFICAÇÃO POR EXERCÍCIO DE CARGOS TÉCNICOS', 81, 122, 'ADMINISTRAÇÃO GERAL', 9.01, 'ASSESSORIA ESPECIAL DO PREFEITO - ADMINISTRAÇÃO DIRETA', '3480,46', '3480,46', 3480.46);
INSERT INTO despesa
(id, acao_codigo, acao_nome, ano_movimentacao, categoria_economica_codigo, categoria_economica_nome, credor_codigo, credor_nome, elemento_codigo, elemento_nome, empenho_ano, empenho_modalidade_codigo, empenho_modalidade_nome, empenho_numero, fonte_recurso_codigo, fonte_recurso_nome, funcao_codigo, funcao_nome, grupo_despesa_codigo, grupo_despesa_nome, indicador_subempenho, mes_movimentacao, modalidade_aplicacao_codigo, modalidade_aplicacao_nome, modalidade_licitacao_codigo, modalidade_licitacao_nome, orgao_codigo, orgao_nome, programa_codigo, programa_nome, subelemento_codigo, subelemento_nome, subempenho, subfuncao_codigo, subfuncao_nome, unidade_codigo, unidade_nome, valor_empenhado, valor_liquidado, valor_pago)
VALUES(7, 2064, 'ASSESSORAMENTO GOVERNAMENTAL', 2019, 3, 'DESPESAS CORRENTES', 0, 'CREDOR NÃO INFORMADO', 11, 'VENCIMENTOS E VANTAGENS FIXAS - PESSOAL CIVIL', 2019, 0, 'SEM TIPO INFORMADO', 5, 100, 'RECURSOS ORDINÁRIOS - NÃO VINCULADOS', 4, 'ADMINISTRAÇÃO', 1, 'PESSOAL E ENCARGOS SOCIAIS', 'x', 2, 90, 'APLICAÇÕES DIRETAS', 0, 'NÃO INFORMADA', 9, 'ASSESSORIA ESPECIAL DO PREFEITO', 2160, 'GESTÃO DAS POLÍTICAS MUNICIPAIS', 32, 'GRATIFICAÇÃO DE CARGOS COMISSIONADOS E FUNÇÕES GRATIFICADAS', 82, 122, 'ADMINISTRAÇÃO GERAL', 9.01, 'ASSESSORIA ESPECIAL DO PREFEITO - ADMINISTRAÇÃO DIRETA', '146446,28', '146446,28', 146446.28);
INSERT INTO despesa
(id, acao_codigo, acao_nome, ano_movimentacao, categoria_economica_codigo, categoria_economica_nome, credor_codigo, credor_nome, elemento_codigo, elemento_nome, empenho_ano, empenho_modalidade_codigo, empenho_modalidade_nome, empenho_numero, fonte_recurso_codigo, fonte_recurso_nome, funcao_codigo, funcao_nome, grupo_despesa_codigo, grupo_despesa_nome, indicador_subempenho, mes_movimentacao, modalidade_aplicacao_codigo, modalidade_aplicacao_nome, modalidade_licitacao_codigo, modalidade_licitacao_nome, orgao_codigo, orgao_nome, programa_codigo, programa_nome, subelemento_codigo, subelemento_nome, subempenho, subfuncao_codigo, subfuncao_nome, unidade_codigo, unidade_nome, valor_empenhado, valor_liquidado, valor_pago)
VALUES(8, 2064, 'ASSESSORAMENTO GOVERNAMENTAL', 2019, 3, 'DESPESAS CORRENTES', 0, 'CREDOR NÃO INFORMADO', 11, 'VENCIMENTOS E VANTAGENS FIXAS - PESSOAL CIVIL', 2019, 0, 'SEM TIPO INFORMADO', 5, 100, 'RECURSOS ORDINÁRIOS - NÃO VINCULADOS', 4, 'ADMINISTRAÇÃO', 1, 'PESSOAL E ENCARGOS SOCIAIS', 'x', 8, 90, 'APLICAÇÕES DIRETAS', 0, 'NÃO INFORMADA', 9, 'ASSESSORIA ESPECIAL DO PREFEITO', 2160, 'GESTÃO DAS POLÍTICAS MUNICIPAIS', 32, 'GRATIFICAÇÃO DE CARGOS COMISSIONADOS E FUNÇÕES GRATIFICADAS', 88, 122, 'ADMINISTRAÇÃO GERAL', 9.01, 'ASSESSORIA ESPECIAL DO PREFEITO - ADMINISTRAÇÃO DIRETA', '134592,67', '134592,67', 134592.67);
INSERT INTO despesa
(id, acao_codigo, acao_nome, ano_movimentacao, categoria_economica_codigo, categoria_economica_nome, credor_codigo, credor_nome, elemento_codigo, elemento_nome, empenho_ano, empenho_modalidade_codigo, empenho_modalidade_nome, empenho_numero, fonte_recurso_codigo, fonte_recurso_nome, funcao_codigo, funcao_nome, grupo_despesa_codigo, grupo_despesa_nome, indicador_subempenho, mes_movimentacao, modalidade_aplicacao_codigo, modalidade_aplicacao_nome, modalidade_licitacao_codigo, modalidade_licitacao_nome, orgao_codigo, orgao_nome, programa_codigo, programa_nome, subelemento_codigo, subelemento_nome, subempenho, subfuncao_codigo, subfuncao_nome, unidade_codigo, unidade_nome, valor_empenhado, valor_liquidado, valor_pago)
VALUES(9, 2064, 'ASSESSORAMENTO GOVERNAMENTAL', 2019, 3, 'DESPESAS CORRENTES', 0, 'CREDOR NÃO INFORMADO', 11, 'VENCIMENTOS E VANTAGENS FIXAS - PESSOAL CIVIL', 2019, 0, 'SEM TIPO INFORMADO', 8, 100, 'RECURSOS ORDINÁRIOS - NÃO VINCULADOS', 4, 'ADMINISTRAÇÃO', 1, 'PESSOAL E ENCARGOS SOCIAIS', 'x', 5, 90, 'APLICAÇÕES DIRETAS', 0, 'NÃO INFORMADA', 9, 'ASSESSORIA ESPECIAL DO PREFEITO', 2160, 'GESTÃO DAS POLÍTICAS MUNICIPAIS', 43, '13º SALÁRIO', 85, 122, 'ADMINISTRAÇÃO GERAL', 9.01, 'ASSESSORIA ESPECIAL DO PREFEITO - ADMINISTRAÇÃO DIRETA', '1720,90', '1720,90', 1720.9);
INSERT INTO despesa
(id, acao_codigo, acao_nome, ano_movimentacao, categoria_economica_codigo, categoria_economica_nome, credor_codigo, credor_nome, elemento_codigo, elemento_nome, empenho_ano, empenho_modalidade_codigo, empenho_modalidade_nome, empenho_numero, fonte_recurso_codigo, fonte_recurso_nome, funcao_codigo, funcao_nome, grupo_despesa_codigo, grupo_despesa_nome, indicador_subempenho, mes_movimentacao, modalidade_aplicacao_codigo, modalidade_aplicacao_nome, modalidade_licitacao_codigo, modalidade_licitacao_nome, orgao_codigo, orgao_nome, programa_codigo, programa_nome, subelemento_codigo, subelemento_nome, subempenho, subfuncao_codigo, subfuncao_nome, unidade_codigo, unidade_nome, valor_empenhado, valor_liquidado, valor_pago)
VALUES(10, 2064, 'ASSESSORAMENTO GOVERNAMENTAL', 2019, 3, 'DESPESAS CORRENTES', 0, 'CREDOR NÃO INFORMADO', 11, 'VENCIMENTOS E VANTAGENS FIXAS - PESSOAL CIVIL', 2019, 0, 'SEM TIPO INFORMADO', 9, 100, 'RECURSOS ORDINÁRIOS - NÃO VINCULADOS', 4, 'ADMINISTRAÇÃO', 1, 'PESSOAL E ENCARGOS SOCIAIS', 'x', 6, 90, 'APLICAÇÕES DIRETAS', 0, 'NÃO INFORMADA', 9, 'ASSESSORIA ESPECIAL DO PREFEITO', 2160, 'GESTÃO DAS POLÍTICAS MUNICIPAIS', 44, 'FÉRIAS', 86, 122, 'ADMINISTRAÇÃO GERAL', 9.01, 'ASSESSORIA ESPECIAL DO PREFEITO - ADMINISTRAÇÃO DIRETA', '12518,50', '12518,50', 12518.5);
